baseURL = "http://example.org/"
languageCode = "en-us"
title = "green | hugo-zwbetz-blog"
publishDir = "docs"
[taxonomies]
  tag = "tags"
[params]
    homeText = "006 favicon is now absURL"
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3